package com.github.hanzm_10.murico.swingapp.config;

public abstract class AbstractResourceConfig extends AbstractConfig {
    @Override
    public String getFilePath() {
        return "";
    }

    @Override
    public String getHeaderComment() {
        return "THIS IS A RESOURCE CONFIGURATION FILE. DO NOT EDIT THIS FILE MANUALLY.";
    }

    /**
     * @return The class that holds the resource configuration. This class must extend
     *         {@link AbstractResourceConfig}.
     */
    public abstract Class<? extends AbstractResourceConfig> getResourceClass();
}
